version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: video-translator-backend
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: video-translator-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_BASE_URL=http://backend:8001
    depends_on:
      - backend
    restart: unless-stopped
